import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import multer from "multer";
import sharp from "sharp";
import { AppError } from "../errors/AppError.js";

const uploadRoot = path.resolve(process.cwd(), "uploads");
const allowedMimeTypes = new Set(["image/jpeg", "image/png", "image/webp", "image/gif"]);
const classTypeMimeTypes = new Set(["image/jpeg", "image/png", "image/webp"]);
const decodedClassTypeFormats = new Set(["jpeg", "png", "webp"]);
const classTypeUploadDir = path.join(uploadRoot, "class-types");
const generatedClassTypeUploadName = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.webp$/i;
const maxClassTypeImageWidth = 8_192;
const maxClassTypeImageHeight = 8_192;
const maxClassTypeImagePixels = 25_000_000;

export const uploadFileSizeLimits = {
  profile: 2 * 1024 * 1024,
  hero: 3 * 1024 * 1024,
  image: 4 * 1024 * 1024
} as const;

export function uploadFileSizeLimitMb(field?: string) {
  if (!field || !(field in uploadFileSizeLimits)) return undefined;
  return uploadFileSizeLimits[field as keyof typeof uploadFileSizeLimits] / (1024 * 1024);
}

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

function storageFor(folder: string) {
  const destination = path.join(uploadRoot, folder);
  ensureDir(destination);

  return multer.diskStorage({
    destination,
    filename: (_req, file, cb) => {
      const ext = path.extname(file.originalname).toLowerCase();
      cb(null, `${crypto.randomUUID()}${ext}`);
    }
  });
}

function imageFileFilter(_req: Express.Request, file: Express.Multer.File, cb: multer.FileFilterCallback) {
  if (!allowedMimeTypes.has(file.mimetype)) {
    cb(new AppError(400, "INVALID_IMAGE_TYPE", "Only jpeg, png, webp and gif images are allowed"));
    return;
  }
  cb(null, true);
}

export function publicUploadUrl(file?: Express.Multer.File) {
  if (!file) return undefined;
  const normalized = file.path.replaceAll("\\", "/");
  const marker = "/uploads/";
  const index = normalized.lastIndexOf(marker);
  return index >= 0 ? normalized.slice(index) : `/uploads/${path.basename(file.path)}`;
}

export const uploadProfile = multer({
  storage: storageFor("profiles"),
  fileFilter: imageFileFilter,
  limits: { fileSize: uploadFileSizeLimits.profile }
});

export const uploadSettings = multer({
  storage: storageFor("settings"),
  fileFilter: imageFileFilter,
  limits: { fileSize: uploadFileSizeLimits.hero }
});

function classTypeImageFilter(_req: Express.Request, file: Express.Multer.File, cb: multer.FileFilterCallback) {
  if (!classTypeMimeTypes.has(file.mimetype)) {
    cb(new AppError(400, "INVALID_IMAGE_TYPE", "Only jpeg, png and webp images are allowed"));
    return;
  }
  cb(null, true);
}

export const uploadClassTypeImage = multer({
  storage: multer.memoryStorage(),
  fileFilter: classTypeImageFilter,
  limits: { fileSize: uploadFileSizeLimits.image, files: 1 }
});

async function normalizeClassTypeImage(file: Express.Multer.File) {
  try {
    const metadata = await sharp(file.buffer, {
      failOn: "warning",
      limitInputPixels: false
    }).metadata();

    if (!metadata.format || !decodedClassTypeFormats.has(metadata.format) || !metadata.width || !metadata.height) {
      throw new AppError(400, "INVALID_IMAGE_CONTENT", "The uploaded file is not a valid jpeg, png or webp image");
    }

    const pixels = metadata.width * metadata.height;
    if (
      metadata.width > maxClassTypeImageWidth
      || metadata.height > maxClassTypeImageHeight
      || pixels > maxClassTypeImagePixels
    ) {
      throw new AppError(
        400,
        "IMAGE_DIMENSIONS_TOO_LARGE",
        `Image dimensions must not exceed ${maxClassTypeImageWidth}x${maxClassTypeImageHeight} or ${maxClassTypeImagePixels} pixels`
      );
    }

    return await sharp(file.buffer, {
      failOn: "warning",
      limitInputPixels: maxClassTypeImagePixels
    })
      .rotate()
      .webp({ quality: 82, alphaQuality: 90, effort: 4 })
      .toBuffer();
  } catch (error) {
    if (error instanceof AppError) throw error;
    throw new AppError(400, "INVALID_IMAGE_CONTENT", "The uploaded file is not a valid jpeg, png or webp image");
  }
}

/** Decodes and stores a metadata-free canonical WebP using a server-generated filename. */
export async function persistClassTypeImage(file: Express.Multer.File) {
  const normalizedImage = await normalizeClassTypeImage(file);

  await fs.promises.mkdir(classTypeUploadDir, { recursive: true });
  const filename = `${crypto.randomUUID()}.webp`;
  const absolutePath = path.join(classTypeUploadDir, filename);
  await fs.promises.writeFile(absolutePath, normalizedImage, { flag: "wx" });
  return `/uploads/class-types/${filename}`;
}

/**
 * Returns the filename only for canonical WebP uploads generated by this API.
 * Bundled/default names and URLs from untrusted origins never identify deletable files.
 */
export function generatedClassTypeUploadKey(imageUrl?: string | null, trustedOrigin?: string | null) {
  if (!imageUrl) return false;

  let pathname: string;
  if (imageUrl.startsWith("/uploads/class-types/")) {
    try {
      pathname = new URL(imageUrl, "http://local.invalid").pathname;
    } catch {
      return null;
    }
  } else {
    if (!trustedOrigin) return null;
    try {
      const parsedImageUrl = new URL(imageUrl);
      const parsedTrustedOrigin = new URL(trustedOrigin);
      if (
        (parsedImageUrl.protocol !== "http:" && parsedImageUrl.protocol !== "https:")
        || parsedImageUrl.origin !== parsedTrustedOrigin.origin
      ) {
        return null;
      }
      pathname = parsedImageUrl.pathname;
    } catch {
      return null;
    }
  }
  if (!pathname.startsWith("/uploads/class-types/")) return null;

  const filename = pathname.slice("/uploads/class-types/".length);
  if (!generatedClassTypeUploadName.test(filename)) return null;
  const target = path.resolve(classTypeUploadDir, filename);
  const relative = path.relative(classTypeUploadDir, target);
  if (!relative || relative.startsWith("..") || path.isAbsolute(relative)) return null;
  return filename.toLowerCase();
}

/** Deletes only a canonical API-generated upload whose resolved path stays in the upload directory. */
export async function deleteLocalClassTypeImage(imageUrl?: string | null, trustedOrigin?: string | null) {
  const filename = generatedClassTypeUploadKey(imageUrl, trustedOrigin);
  if (!filename) return false;
  const target = path.resolve(classTypeUploadDir, filename);

  try {
    await fs.promises.unlink(target);
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw error;
  }
}
